# Generated by Django 4.2.4 on 2023-08-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainresponse',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_responses', to='domain_responses.domain'),
        ),
    ]
